(function(g){var window=this;var s4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.C,displayName:g.mI(a),kind:a.A,name:a.B,id:a.ka,is_servable:a.M,is_default:a.isDefault,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},t4=function(a){return a.g?a.g.languageCode:a.l},Yya=function(a,b){var c=new g.lI;
c.l=a.l;c.C=a.C;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},Zya=function(a){a=g.od(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Hd(a[b])},$ya=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},u4=function(a){if(!aza.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(bza,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},v4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.pQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.l=k},w4=function(a,b,c,d,e){g.pQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},y4=function(a){a=void 0===a?{}:a;
var b="_"+x4++;return new w4(0,0x8000000000000,0,b,a)},z4=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.ib);a.params.ib&&g.Ga(l,a.params.ib);g.Ga(l,c.ib);k.ib=l;g.W.call(this,{G:"div",L:"caption-window",U:{id:"caption-window-"+a.id,dir:1==k.jk?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{G:"span",L:"captions-text"}]});this.o=[];this.I=!1;this.D=a;this.C=[];this.F=[];this.pa=e;this.oa=f;this.B=null;this.P=.96*e;this.da=.96*f;this.l=k;this.ma=c;this.A=this.ua["captions-text"];this.fa=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.K=d/360*16;this.type=0;this.Y=this.K*cza(l);a=new g.LF(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.qN,this);a.subscribe("dragmove",this.pN,this);a.subscribe("dragend",this.oN,this);this.ba=this.ca=0;a="";this.l.vk&&(a=u4(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.vk+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":dza[this.l.textAlign]};this.fa&&(b["border-radius"]=a?this.Y/
8+"px":"");g.ph(this.element,b);switch(this.l.Sg){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},cza=function(a){var b=1+.25*(a.mj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},A4=function(a,b){var c={},d=b.background?b.background:a.l.ib.background;
if(null!=b.Ze||b.background){var e=null!=b.Ze?b.Ze:a.l.ib.Ze;d=u4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.fa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Y/8+"px")}if(null!=b.mj||null!=b.offset)c["font-size"]=a.K*cza(b)+"px";d=1;e=b.color||a.l.ib.color;if(b.color||null!=b.Eh)e=u4(e),d=null==b.Eh?a.l.ib.Eh:b.Eh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Vh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Qw&&
(k=e=b.Qw);var l=a.K/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.AE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.ib.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.zs&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Ir&&(c.visibility="hidden");return c},eza=function(a,b,c){a.I=a.I||!!c;
var d={};g.Ga(d,a.l.ib);g.Ga(d,c||b.l);g.Ga(d,a.ma.ib);c=a.C[0];if(c&&d.background==c.background&&d.Ze==c.Ze&&!!d.Ir==!!c.Ir&&d.Vh==c.Vh){var e;for(e=0;e<a.C.length;e++)if($ya(d,a.C[e])){var f=a.F[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Bd("SPAN");g.ph(f,A4(a,e));a.F[0].appendChild(f);e=1}a.F.length=e;a.C.length=e}else a.F.length=0,a.C.length=0,f=g.Bd("SPAN"),g.ph(f,A4(a,d)),a.A.appendChild(f);a.B&&a.B.parentNode!=f&&(g.Hd(a.B),f.appendChild(a.B));c=(k=g.v(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.o.length||!b.C){if(0<e||0!=a.o.length){var m=g.Bd("BR");f.appendChild(m)}f.appendChild(g.Cd("\u00a0"));a.B=g.Cd("\u00a0");f.appendChild(a.B)}l&&(m=a.B,m.parentNode&&m.parentNode.insertBefore(k?g.Cd(l):l,m))}a.C.push(d);a.F.push(f);a.o.push(b)},fza=function(){},C4=function(){this.A=this.l=this.mode=this.o=0;
this.B=new B4(this);this.C=new B4(this);this.g=[];this.clear()},hza=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Qm:a,
Rm:b,result:0};a=gza[a];b=gza[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{Qm:a,Rm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Qm:a,Rm:b,result:2};return{Qm:a,Rm:b,result:3}},jza=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,iza(a.B,b,c,d))},kza=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?jza(a,d.Lw,d.Mw,b):1==d.type&&a.o&496&&iza(a.C,d.Lw,d.Mw,b)}a.g.length=0},D4=function(){this.g=0},E4=function(){this.l=this.o=this.g=0},F4=function(){this.timestamp=this.ye=0},G4=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new F4}this.g=this.l=this.Kc=0;this.style=new D4;this.B=a;this.A=0},H4=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.ye){0==c&&(c=m,d=q);n=String.fromCharCode(r.ye);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.ye||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.A(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.ye,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==r)l&&b.A(c,d,e,f,l),e=f,l="",d=c=0},pza=function(a,b){switch(a){case 0:return lza[(b&127)-32];
case 1:return mza[b&15];case 2:return nza[b&31];case 3:return oza[b&31]}return 0},I4=function(a){return a.o[a.Kc][a.l]},J4=function(a,b,c){2<=b&&1<a.l&&(--a.l,I4(a).ye=0);
var d=I4(a);d.timestamp=a.B.l+0;d.ye=pza(b,c);32>a.l&&a.l++},qza=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].kn(a.o[c+e][f])},K4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},L4=function(a){a.Kc=0<a.g?a.g:1;
a.l=1;K4(a,0,15)},M4=function(a){this.A=a;
this.B=0;this.style=new D4;this.C=new G4(a);this.D=new G4(a);this.F=new G4(a);this.l=this.C;this.o=this.D;this.g=this.l},N4=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:H4(d,c),L4(a.l),L4(a.o),d.Kc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(H4(d,c),K4(d,d.Kc-d.g,b)):d.Kc<b&&(b=d.g),d.g=b)},rza=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},sza=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},B4=function(a){this.l=a;
this.g=new E4;this.B=0;this.o=new M4(a);this.C=new M4(a);this.A=this.o},iza=function(a,b,c,d){a.g.update();
b=hza(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Qm;c=b.Rm;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&J4(a,0,b),c&96&&J4(a,0,c),0!=b&&0!=c&&3==a.style.g&&H4(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.Kc;break;case 3:if(d!=c.Kc){if(d<c.g&&(d=c.g,d==c.Kc))break;var f=1+c.Kc-c.g,k=1+d-c.g;qza(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));K4(c,b,e)}}c.Kc=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:J4(b.g,0,32);break a;case 48:57==c?(b=b.g,I4(b).ye=0,32>b.l&&b.l++):J4(b.g,1,c&15)}break;case 2:c&32&&J4(b.g,2,c&31);break;case 3:c&32&&J4(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:rza(b);break;case 33:b=
b.g;1<b.l&&(--b.l,I4(b).ye=0);break;case 36:b=b.g;d=I4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:N4(b,2,d);break;case 38:N4(b,3,d);break;case 39:N4(b,4,d);break;case 40:J4(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);L4(d);sza(b);break;case 43:sza(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:H4(a,d)}K4(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Kc){++a.Kc;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.Kc<a.g&&(a.Kc=a.g));b=a.Kc-a.g+1;H4(a,d);qza(a,b,b+1,a.g-1);K4(a,a.Kc,1)}break;case 46:K4(b.o,0,15);break;case 47:H4(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;rza(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},O4=function(){},P4=function(a){this.l=a;
this.g=null},uza=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Vr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");tza(d,e,k,b,f,a.firstChild,{},c)},tza=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.zs=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");Q4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new v4(a,b,c,d,n.nodeValue,e||0<m,g.Xb(k)?void 0:k));else{var q={};g.Ga(q,k);tza(a,b,c,d,e||0<m,n,q,l)}}},R4=function(){this.l={};
this.g=null},S4=function(a){this.A={};
this.I={};this.K={};this.B="_"+x4++;this.C=a;this.H={};this.g=null;this.D=[];this.l=null;this.F=!0},T4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},U4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},V4=function(a,b){var c=T4(a,b);
if(void 0!=c)return c},W4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Q4.test(c),c},vza=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.K[d]:a.C);d=V4(b,"mh");null!=d&&(c.Ms=d);d=V4(b,"ju");null!=d&&(c.textAlign=d);d=V4(b,"pd");null!=d&&(c.jk=d);d=W4(b,"wfc");null!=d&&(c.windowColor=d);d=T4(b,"wfo");void 0!=d&&(c.vk=d/255);return c},wza=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.I[d]);d=V4(b,"ap");null!=d&&(c.Sg=d);d=T4(b,"cc");null!=d&&(c.RH=d);d=T4(b,"ah");null!=d&&(c.ti=d);d=T4(b,"rc");null!=d&&(c.fp=d);d=T4(b,"av");null!=d&&(c.Qi=d);return c},xza=function(a,b,c,d){var e={};
g.Ga(e,wza(a,b));g.Ga(e,vza(a,b));d?$ya(e,a.C)?(d=a.B,e=a.C):d="_"+x4++:d=b.getAttribute("id")||"0";a=T4(b,"t")+c;b=T4(b,"d")||0x8000000000000;return new w4(a,b,0,d,e)},zza=function(a,b,c){var d=[],e=b.getAttribute("w")||a.B,f=!!U4(b,"a");
c=(T4(b,"t")||0)+c;var k=T4(b,"d")||5E3;f||(!a.F&&a.l&&a.l.windowId==e&&a.l.end>c&&(a.l.end=c),a.l&&"\n"==a.l.text&&(a.l.text=""));var l=f?6:5,m=a.A[b.getAttribute("p")],n=b.childNodes;n.length&&(a.F=null!=b.getAttribute("d"));b={};for(var q=0;q<n.length;b={Dh:b.Dh},q++){var r=n[q];b.Dh=void 0;0<q&&(f=!0);var u=void 0;1==r.nodeType&&(u=r);b.Dh=u&&"s"==u.tagName?yza(a,u,c,k,e,f,l):new v4(c,k,l,e,r.textContent||"",f,m);if(!f&&(r=a.D.find(function(a){return function(b){return b.text===a.Dh.text&&b.windowId===
a.Dh.windowId}}(b)))){r.end=b.Dh.end;
a.l=r;continue}d.push(b.Dh);a.l=b.Dh}return d},yza=function(a,b,c,d,e,f,k){var l=b.textContent?b.textContent:"";
a=a.A[b.getAttribute("p")];b=T4(b,"t")||0;return new v4(c+b,d-b,k,e,l,f,a)},X4=function(a,b,c){this.D=c;
this.version=this.B=this.C=this.g=0;this.l=new window.DataView(a);this.o=[]},Y4=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},Aza=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},Z4=function(a,b){this.l=a;
this.track="CC3"==b.C?4:0;this.g=new C4;this.g.o=1<<this.track},Cza=function(a){if(g.v(a))return!1;
a=new X4(a,8,0);return Bza(a)},Bza=function(a){if(!(a.g<a.l.byteLength)||1380139777!=Aza(a))return!1;
a.version=Y4(a);if(1<a.version)return!1;Y4(a);Y4(a);Y4(a);return!0},Dza=function(){this.l=[];
this.g=[]},$4=function(a,b){return b?a.g.concat(a.l):a.g},a5=function(a,b){switch(b.A){case "asr":var c=a.l;
g.La(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.La(c,(0,g.z)(b.I,b))||c.push(b)}},b5=function(){this.g=null},Eza=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.zs=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new v4(b,c,d,e.id,q.nodeValue,f||0<n,g.Xb(l)?void 0:l),m.push(q),e!=a.g&&e.l.push(q);else{var r={};g.Ga(r,l);Eza(a,b,c,d,e,!0,q,r,m)}}},c5=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},d5=function(a){g.L.call(this);
this.ez=!!a;this.l=new Dza;this.D=[];this.g=null},Gza=function(a){var b={};
if(a=t4(a))b.lang=a,Fza.test(a)&&(b.jk=1);return b},Hza=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.v(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.HI(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),Cza(b)||(b=g.ce(new window.Uint8Array(b))))}if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new b5),a.g.o(b,d);b=g.Vr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new S4(Gza(c)):a.g=new R4:a.g=new P4(Gza(c)));return a.g.o(b,d)}try{if(Cza(b))return a.g||(a.g=
new Z4(e,c)),a.g.o(b,d)}catch(k){g.PD(k)}return[]},e5=function(a){d5.call(this,a.Xm);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},f5=function(){this.ob=[]},g5=function(a,b,c,d,e,f){g.L.call(this);
this.K=a;this.A=b;this.C=new f5;this.g=null;this.H=d;this.M=f;this.l=this.o=null;this.F=c;this.D=e||!1;this.I=new g.Yt(this.xz,1E3,this);g.M(this,this.I);this.B=new g.GF(this);g.M(this,this.B);this.B.O(b,"seekto",this.CA);this.CA(b.getCurrentTime());this.xz()},Iza=function(a,b){var c=a.g;
a.g=g.Ia(a.F.fh(b).Da);c!=a.g&&a.M&&a.M()},Jza=function(a,b){var c=g.mK(b,a.K,{}).Ra(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.l=g.OE(c,d,3,100).then((0,g.z)(a.YR,a));a.o=b;c=a.C;d=a.o.Da[0].wa;var e=g.eb(c.ob,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.ob[e-1]&&e<c.ob.length&&1==c.ob[e]-d?(g.Sa(c.ob,e),g.Sa(c.ob,e-1)):0<e&&1==d-c.ob[e-1]?c.ob[e-1]=d:e<c.ob.length&&1==c.ob[e]-d?c.ob[e]=d:(g.$a(c.ob,e,0,d),g.$a(c.ob,e+1,0,d)))},h5=function(a,b){d5.call(this);
this.o=a;this.A=b;this.B=null;this.C=!1},Kza=function(a,b){if(b in a.o.g)return a.o.g[b];
if(g.LK(a.o))for(var c in a.o.g){var d=a.o.g[c];if(g.jH(d.info.mimeType)&&("386"!=c||g.Y(a.A).experiments.g("html5_manifestless_captions_fmt3")))return d}return null},Lza=function(a,b){return a.za||g.Y(b).Ma&&null!=a.ra&&null!=a.ra.g.rawcc},i5=function(a,b,c,d,e,f){z4.call(this,a,b,c,d,e,f);
this.type=1},j5=function(a,b,c,d,e,f){z4.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.H=this.M=0;this.N=window.NaN;this.ia=null;this.X=new g.Yt(this.cS,433,this);g.M(this,this.X)},k5=function(a){if(!a.M){var b=g.Bd("SPAN");
g.ph(b,A4(a,a.l.ib));a.A.appendChild(b);b.appendChild(g.Cd("M"));var c=b.offsetHeight,d=g.Bd("BR");b.appendChild(d);b.appendChild(g.Cd("M"));a.M=b.offsetHeight-c;a.A.removeChild(b)}return a.M},l5=function(a,b,c,d){d5.call(this,d);
c=c||g.iE(a).hl||"";c=c.split("_").join("-");this.B=g.kE(a,{hl:c});this.A=b;this.C={};this.o=null},o5=function(a){g.rV.call(this,a);
g.UG({YTP_CLICK_FOR_SETTINGS:"\u70b9\u51fb $GEAR_ICON \u67e5\u770b\u8bbe\u7f6e",YTP_SAMPLE_SUBTITLES:"\u5b57\u5e55\u6837\u5f0f\u9884\u89c8"});this.A=g.Y(a);this.l=a.ea();this.oa=g.VU(a);this.K=a;var b=null,c=g.lD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.VC(c));this.ba=b;this.C={ib:{}};this.H={ib:{}};this.M=[];this.P={};this.Y={};this.N=!1;this.pa="1"==this.l.qc.cc_auto_caps||"1"==this.A.Tb.cc_auto_caps;b="3"==this.A.o&&!!a.app.B&&!!a.app.B.g.textTracks;this.F=(c=this.A.experiments.g("web_player_native_controls_live_captions_fix"))?
b&&!this.l.za:b;this.ia=c&&b&&this.l.za;c=b=this.o=this.B=this.D=this.I=this.X=this.ma=null;this.F||(b=new g.Vt(this.bE,void 0,this),g.M(this,b),c=new g.Yt(this.KT,2E3,this),g.M(this,c));this.da=b;this.fa=c;this.W=new g.GF(this);g.M(this,this.W);this.F||this.W.O(a,"resize",this.Ru);this.W.O(a,"onPlaybackAudioChange",this.aP);this.W.O(a,"crn_captions",this.AL,this);this.W.O(a,"crx_captions",this.BL,this);m5(this,n5(this,"display-settings")||{})},Mza=function(a){if(a.l.captionTracks.length)var b=a.g.getAudioTrack().Iw;
if("FORCED_ON"==b||1==a.A.Wg||1==a.l.Wg||"alwayson"==g.lO(a.l,"yt:cc"))return!0;if(2==a.A.Wg){var c=n5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.lO(a.l,"yt:cc")},Nza=function(a,b){if(a.B){var c=$4(a.B.l,b||a.pa);
if(a.D&&a.D.g)return a.D.g;for(var d=[a.l.Vg,a.A.Vg,g.lO(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(t4(c[f])==d[e])return c[f];return a.D&&a.D.Rq?a.D.Rq:(d=c.find(function(a){return a.isDefault}))?d:c[0]||a.D&&a.D.Mk}return null},Oza=function(a,b){for(var c=a.K.app.B.g.textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},p5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.N=c);a.o=b;a.load(d)},Pza=function(a,b){var c=g.C_(a.oa,!0).height;
if(!c)return null;var d=a.oa.Pa();switch(null!=b.params.Ms?b.params.Ms:b.params.yU?2:1<b.l.length?1:0){case 1:return new i5(b,a.C,a.H,c,d.width,d.height);case 2:return new j5(b,a.C,a.H,c,d.width,d.height);default:return new z4(b,a.C,a.H,c,d.width,d.height)}},m5=function(a,b,c){var d=q5.ib;
a.C={};g.Ga(a.C,q5);a.C.ib={};g.Ga(a.C.ib,d);a.H={ib:{}};var e=b.backgroundOverride?a.H:a.C,f=b.background||d.background;Q4.test(f);e.ib.background=f;e=b.colorOverride?a.H:a.C;f=b.color||d.color;Q4.test(f);e.ib.color=f;e=b.windowColorOverride?a.H:a.C;f=b.windowColor||q5.windowColor;Q4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.H:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ze);e.ib.Ze=f;e=b.fontSizeIncrementOverride?a.H:a.C;f=b.fontSizeIncrement;null==f&&(f=d.mj);e.ib.mj=f;e=b.textOpacityOverride?
a.H:a.C;f=b.textOpacity;null==f&&(f=d.Eh);e.ib.Eh=f;e=b.windowOpacityOverride?a.H:a.C;f=b.windowOpacity;null==f&&(f=q5.vk);e.vk=f;e=b.charEdgeStyleOverride?a.H:a.C;f=b.charEdgeStyle;null==f&&(f=d.Vh);e.ib.Vh=f;e=b.fontFamilyOverride?a.H:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ib.fontFamily=f;a.loaded&&a.Ru();c&&r5(a,"display-settings",b)},Rza=function(a,b){if(b&&!a.I){var c=y4({jk:0,
lang:"zh-CN"});a.I=[c,new v4(c.start,c.end-c.start,0,c.id,g.V("YTP_SAMPLE_SUBTITLES"))];g.gV(a.g,a.I)}else!b&&a.I&&(Qza(a,a.I),a.I=null)},Qza=function(a,b){g.iV(a.g,b);
(0,g.B)(b,function(a){g.Ta(this.M,a)},a);
a.da.Vk()},Sza=function(a,b){return a&&g.v(a)&&Q4.test(a)?a:b},Tza=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Vza=function(a,b){if(a&&g.v(a)){var c=Uza.indexOf(a);
return-1!=c?c:b}return b},Xza=function(a,b){if(a&&g.v(a)){var c=Wza.indexOf(a);
return-1!=c?c:b}return b},Yza=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?g.$c(a,-2,4):b},n5=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},r5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.rI.prototype.Kn=g.da(2,function(a){return(a=this.ci(a))?a.l:0});
g.BK.prototype.Kn=g.da(1,function(){return 0});
g.lI.prototype.I=g.da(0,function(a){return a?this.toString()==a.toString():!1});
var Fza=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,bza=/#(.)(.)(.)/,aza=/^#(?:[0-9a-f]{3}){1,2}$/i,Q4=/^#(?:[0-9a-f]{3}){1,2}$/i,Wza="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Uza=["none","raised","depressed","uniform","dropShadow"];var dza=["left","right","center"];var q5={windowColor:"#080808",vk:0,textAlign:2,Sg:7,ti:50,Qi:100,ib:{background:"#080808",Ze:.75,Vh:0,color:"#fff",fontFamily:4,mj:0,Eh:1,offset:1}};g.p(v4,g.pQ);g.p(w4,g.pQ);var x4=0;g.p(z4,g.W);g.h=z4.prototype;g.h.qN=function(a,b){var c=g.Fh(this.element,this.element.parentElement);this.ca=a-c.x;this.ba=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.pN=function(a,b){var c=g.Ih(this.element),d=a-this.ca-.02*this.pa,e=b-this.ba-.02*this.oa,f=(d+c.width/2)/this.P*3;f=Math.floor(g.$c(f,0,2));var k=(e+c.height/2)/this.da*3;k=Math.floor(g.$c(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.P;d=100*g.$c(d,0,1);c=(e+k/2*c.height)/this.da;c=100*g.$c(c,0,1);this.D.params.Sg=l;this.D.params.Qi=c;this.D.params.ti=d;this.l.Sg=l;this.l.Qi=c;this.l.ti=d;this.SC()};
g.h.oN=function(){g.tq(this.element,"ytp-dragging")};
g.h.SC=function(){this.Mi(this.o)};
g.h.Xb=function(){return this.type};
g.h.Mi=function(a){var b=Math.min(this.ay(),this.P),c=this.Zx();g.ph(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.qq(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.ti+2,e=this.l.Sg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.Qi+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ph(this.element,a)};
g.h.qq=function(a){var b;for(b=0;b<a.length&&a[b]==this.o[b];b++);if(this.I||this.o.length>b)b=0,this.I=!1,this.o=[],this.C=[],this.F=[],this.B=null,g.Fd(this.A);for(;b<a.length;b++)eza(this,a[b])};
g.h.ay=function(){return 0};
g.h.Zx=function(){return 0};fza.prototype.A=function(){};C4.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
C4.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var gza=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];D4.prototype.set=function(a){this.g=a};
D4.prototype.get=function(){return this.g};
E4.prototype.clear=function(){this.g=0};
E4.prototype.update=function(){this.g=2==this.g?1:0};
E4.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
F4.prototype.kn=function(a){this.ye=a.ye;this.timestamp=a.timestamp};
F4.prototype.reset=function(){this.timestamp=this.ye=0};
G4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.ye?a+"_":a+String.fromCharCode(d.ye)}a+="\n"}return a};
G4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.Kc=1};
var lza=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],mza=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],nza=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],oza=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];M4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
B4.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};O4.prototype.reset=function(){};g.p(P4,O4);P4.prototype.o=function(a){var b=[];this.g||(this.g=y4(this.l),b.push(this.g));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())uza(c.value,this.g.id,b);return b};g.p(R4,O4);
R4.prototype.o=function(a){var b=[];this.g||(this.g=y4(),this.l[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.l[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=y4());
var k={};f&&(g.Ga(k,f.params),f=f.params.ib)&&(k.ib={},g.Ga(k.ib,f));e.getAttribute("rc")&&(k.fp=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.RH=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Sg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ti=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Qi=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.jk=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.jk=0));e.getAttribute("bc")&&(k.ib||(k.ib={}),k.ib.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.ib||(k.ib={}),k.ib.Ze=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.ib||(k.ib={}),k.ib.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.yU=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new w4(c,f,0,e,k)}else c=null}this.l[d]=c;b.push(c);break;case "text":for(d=[],uza(a,this.g.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.l[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(S4,O4);S4.prototype.reset=function(){this.H={};this.g=null;this.D=[];this.l=null;this.F=!0};
S4.prototype.o=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);for(var c,d,e=g.ma(a.firstChild.childNodes),f=e.next();!f.done;f=e.next())if(f=f.value,1==f.nodeType)switch(f.tagName){case "head":c=f;break;case "body":d=f}if(c)for(c=g.ma(c.childNodes),e=c.next();!e.done;e=c.next())if(e=e.value,1==e.nodeType)switch(e.tagName){case "pen":f=e.getAttribute("id");var k=this.A,l={},m=e.getAttribute("p");m&&g.Ga(l,this.A[m]);m=U4(e,"b");null!=m&&(l.bold=m);m=U4(e,"i");null!=m&&
(l.zs=m);m=U4(e,"u");null!=m&&(l.underline=m);m=V4(e,"et");null!=m&&(l.Vh=m);m=V4(e,"of");null!=m&&(l.offset=m);m=W4(e,"bc");null!=m&&(l.background=m);m=W4(e,"ec");null!=m&&(l.Qw=m);m=W4(e,"fc");null!=m&&(l.color=m);m=V4(e,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=T4(e,"sz");void 0!=m&&(l.mj=m/100-1);m=T4(e,"bo");void 0!=m&&(l.Ze=m/255);e=T4(e,"fo");void 0!=e&&(l.Eh=e/255);k[f]=l;break;case "ws":f=e.getAttribute("id");this.K[f]=vza(this,e);break;case "wp":f=e.getAttribute("id"),this.I[f]=wza(this,
e)}if(d){c=b;e=[];f=[];d=g.ma(d.childNodes);for(k=d.next();!k.done;k=d.next())if(k=k.value,1==k.nodeType)switch(k.tagName){case "w":this.g=xza(this,k,c,!1);(k=this.H[this.g.id])&&k.end>this.g.start&&(k.end=this.g.start);this.H[this.g.id]=this.g;e.push(this.g);break;case "p":if(l=zza(this,k,c),0<l.length)for(l[0].windowId==this.B&&(this.g=xza(this,k,c,!0),e.push(this.g)),k=g.ma(l),l=k.next();!l.done;l=k.next())l=l.value,l.windowId=this.g.id,this.g.l.push(l),f.push(l),e.push(l)}this.D=f;d=e}else d=
[];return d};g.p(X4,fza);X4.prototype.A=function(a,b,c,d,e){if(c<d){var f="_"+x4++;c=c/1E3-this.D;d=d/1E3-this.D;a=new w4(c,d-c,5,f,{textAlign:0,Sg:0,ti:2.5*b,Qi:5.33*a});e=new v4(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.p(Z4,O4);Z4.prototype.o=function(a){a=new X4(a,a.byteLength,this.l);if(Bza(a)){for(;a.g<a.l.byteLength;)for(0==a.version&&(a.C=Aza(a)*(1E3/45)),a.B=Y4(a);0<a.B;a.B--){var b=Y4(a),c=Y4(a),d=Y4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.C,type:this.track,Lw:c,Mw:d,order:b.g.length}))}kza(this.g,a);return a.o}return[]};
Z4.prototype.reset=function(){this.g.clear()};g.p(b5,O4);
b5.prototype.o=function(a,b){for(var c=[],d=a.split(Zza),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!$za.test(f)){var l=s5.exec(f);if(l&&3<=l.length){var m=c5(l[1]);l=c5(l[2])-m;m+=k;f=f.substring(s5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");s5.lastIndex=0;var n=f;f={};this.g||(this.g=y4({Ms:0}),c.push(this.g));var q=this.g;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new v4(m,l,k,q.id,n,!1,g.Xb(f)?void 0:f));else{n=n.split(aAa);1!=n.length&&(k=6,q="_"+bAa++,q=new w4(m,l,k,q,{}),c.push(q));
for(var r=m,u=0;u<n.length;u++){var C=n[u];if(0==u%2){var H=g.Vr("<html>"+C+"</html>");if(H.getElementsByTagName("parsererror").length){var T=H.createElement("span");T.appendChild(H.createTextNode(C))}else T=H.firstChild;Eza(this,r,l-(r-m),k,q,0<u,T,f,c)}else r=c5(C)}}}s5.lastIndex=0}}return c};
var bAa=0,$za=/^NOTE/,Zza=/(?:\r\n|\r|\n){2,}/,s5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),aAa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(d5,g.L);d5.prototype.trackCount=function(){return $4(this.l,!0).length};
d5.prototype.Ld=function(){this.g=null};
d5.prototype.V=function(){g.L.prototype.V.call(this);this.Ld()};
d5.prototype.AC=function(){return!1};g.p(e5,d5);g.h=e5.prototype;g.h.Gs=function(a,b){var c=this.Tk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Ld();this.o=g.rE(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.Hs=function(a,b,c,d){this.A=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())a5(this.l,c.value);a()};
g.h.Tk=function(a){var b=a.Ra(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.kE(b,c)};
g.h.Ld=function(){d5.prototype.Ld.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Ld();d5.prototype.V.call(this)};f5.prototype.contains=function(a){a=g.eb(this.ob,a);return 0<=a||0>a&&1==(-a-1)%2};
f5.prototype.length=function(){return this.ob.length/2};g.p(g5,g.L);g.h=g5.prototype;g.h.V=function(){g.L.prototype.V.call(this);this.l&&this.l.cancel()};
g.h.CA=function(a){var b=this;if(this.F.xc())var c=this.B.O(this.A,"progresssync",function(){b.F.index.Ob()&&(b.reset(),b.g=null,Iza(b,b.A.getCurrentTime()),b.B.Ba(c))});
else Iza(this,a)};
g.h.reset=function(){this.C=new f5;this.l&&(this.l.cancel(),this.l=null)};
g.h.xz=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.yi(a);!a||this.l||this.g&&30<this.g.startTime-this.A.getCurrentTime()||(a=this.g,a=a.g.rl(a),!g.Y(this.A).experiments.g("disable_captions_unknown_requests")&&!a.Da[0].duration)||(this.C.contains(a.Da[0].wa)||Jza(this,a),this.g=g.Ia(a.Da));this.I.start()};
g.h.YR=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status;if(!g.Y(this.A).experiments.g("disable_captions_redirects_redux")){var c=g.GK(a);if(c){a=g.mK(this.o,this.K,{});b=this.o;g.iK(b.g,a,c);b.requestId=a.get("req_id");Jza(this,this.o);return}}b||null===this.H||(this.D?this.H(a.response,1E3*this.o.Da[0].startTime):this.H(a.responseText,1E3*this.o.Da[0].startTime));this.l=this.o=null};g.p(h5,d5);g.h=h5.prototype;g.h.Gs=function(a,b){this.Ld();var c=Kza(this,a.l);if(c){var d=c.index.Kn(c.index.Ff());g.Y(this.A).experiments.g("html5_disable_caption_starttime")||(d-=c.index.Kd(c.index.Ff()));d*=1E3;var e=g.Y(this.A).Ma;this.B=new g5(new g.SJ,this.A,c,function(c,e){b(c,a,e,d)},e||g.gH(c.info),(0,g.z)(function(){e&&(this.B&&this.B.reset(),this.g&&this.g.reset(),this.C=!0)},this))}};
g.h.AC=function(){var a=this.C;this.C=!1;return a};
g.h.Hs=function(a){if(g.Y(this.A).Ma)a5(this.l,new g.lI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),a5(this.l,new g.lI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.o.g)g.jH(this.o.g[b].info.mimeType)&&"rawcc"!=b&&("386"!=b||g.Y(this.A).experiments.g("html5_manifestless_captions_fmt3"))&&a5(this.l,new g.lI({format:1,languageCode:b,languageName:"English",
name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:"."+b}));a()};
g.h.Ld=function(){d5.prototype.Ld.call(this);this.B&&(this.B.dispose(),this.B=null)};
g.h.Tk=function(){return""};
g.h.V=function(){this.Ld();d5.prototype.V.call(this)};g.p(i5,z4);i5.prototype.qq=function(a){var b=this.D.l;z4.prototype.qq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ga(d,c.l);g.Ga(d,cAa);var e=c.l;var f=d}eza(this,c,d)}};
var cAa={Ir:!0};g.p(j5,z4);g.h=j5.prototype;g.h.SC=function(){g.$t(this.X)};
g.h.cS=function(){g.tq(this.element,"ytp-rollup-mode");this.Mi(this.ia,!0)};
g.h.ay=function(){return this.H};
g.h.Zx=function(){return this.D.params.fp*k5(this)};
g.h.Mi=function(a,b){this.ia=a;if(k5(this)){for(var c=0,d=0;d<this.o.length&&c<a.length;d++)this.o[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.o.concat(a.slice(c)));c=this.H;this.H=0;z4.prototype.Mi.call(this,a);this.H=Math.max(c,this.A.offsetWidth+1);c=this.D.params.fp*k5(this)-this.A.offsetHeight;c!=this.N&&(b||(0,window.isNaN)(this.N)||(g.S(this.element,"ytp-rollup-mode"),g.Zt(this.X)),g.ph(this.A,"transform",c?"translateY("+c+"px)":""),this.N=c);z4.prototype.Mi.call(this,a)}else z4.prototype.Mi.call(this,
a)};g.p(l5,d5);g.h=l5.prototype;g.h.Gs=function(a,b){var c=this.Tk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Ld();this.o=g.rE(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.Hs=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.ez&&(b.asrs=1);d=g.kE(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),u=m.getAttribute("kind"),C=m.getAttribute("id"),H="true"==m.getAttribute("lang_default"),
T="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");a5(d,new g.lI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:u,id:C,is_servable:!0,is_translateable:T,vss_id:m,is_default:H}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),u="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:q,id:r,
is_default:u},this.C[l.languageCode]=l.languageName,this.D.push(new g.kI(l))}a()},this);
this.Ld();this.o=g.rE(d,{format:"RAW",Hb:b,withCredentials:!0})};
g.h.Tk=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.B,kind:a.A,fmt:a.o};a.g&&(c.tlang=t4(a));return b=g.kE(b,c)};
g.h.Ld=function(){d5.prototype.Ld.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Ld();d5.prototype.V.call(this)};g.p(o5,g.rV);g.h=o5.prototype;g.h.V=function(){if(this.F){var a=this.K.app.B;a&&Zya(a)}else Rza(this,!1);g.rV.prototype.V.call(this)};
g.h.Yz=function(){return this.F?!this.l.za:this.ia||this.l.captionTracks.length&&this.g.getAudioTrack().Mk?!0:Mza(this)};
g.h.load=function(a){g.rV.prototype.load.call(this);this.D=this.g.getAudioTrack();if(this.B||a)this.o?(this.F&&!this.A.experiments.g("disable_native_caption_api")?Oza(this,!0):a?this.kC(a,this.o):3!=this.g.Ta()&&this.B.Gs(this.o,(0,g.z)(this.kC,this)),this.g.sa("captionschanged",s4(this.o))):this.g.sa("onCaptionsTrackListChanged");else{var b;Lza(this.l,this.K)?b=new h5(this.l.ra,this.g):this.l.captionTracks.length?b=new e5(this.l):b=new l5(this.l.Ym,this.l.videoId,this.l.Vg||this.A.Vg||g.lO(this.l,
"yt:cc_default_lang")||this.A.Ca,this.l.Xm);this.B=b;b.Hs((0,g.z)(this.FS,this),!0,this.F?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.F?this.A.experiments.g("disable_native_caption_api")?Zya(this.K.app.B):this.o&&Oza(this,!1):(this.fa&&g.au(this.fa),g.jV(this.g,"captions"),this.M=[],this.B&&this.B.Ld(),this.I&&g.gV(this.g,this.I),this.Ru());g.rV.prototype.unload.call(this);var a=g.TU(this.g.app);a&&a.C&&g.qP(a.C.o);this.g.sa("captionschanged",{})};
g.h.FS=function(){if(this.N||Mza(this))var a=Nza(this,this.N);if(this.F||this.ia){for(var b=$4(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.mI(e),srclang:t4(e),id:e.toString()};this.ia||(f.src=this.B.Tk(e));e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}a=this.K.app.B;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.K.app.B.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.A.experiments.g("disable_native_caption_api")&&this.W.O(c.textTracks,"change",this.GS)}else!this.o&&
a&&p5(this,a),this.g.sa("onCaptionsTrackListChanged"),this.g.sa("onApiChange")};
g.h.GS=function(){for(var a=this.K.app.B.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=$4(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&p5(this,b,!0)};
g.h.IU=function(){this.A.experiments.g("disable_native_caption_api")?this.loaded&&!this.F&&this.unload():!this.o&&this.F||this.unload()};
g.h.kC=function(a,b,c,d){if(a){this.B.AC()&&(this.M=[],g.jV(this.K,"captions"),this.da.Vk());a=Hza(this.B,a,b,c,d);g.gV(this.g,a);if(this.N&&(a={trackName:b.B,trackKind:b.A,trackLangCode:t4(b)},b.g&&(a.fromLangCode=b.l),g.aV(this.g,"cc",a),!this.ia&&this.o!=(this.D&&this.D.Mk))){!this.N||g.uM(this.A)||g.BM(this.A)||(g.au(this.fa),b=y4({Sg:0,ti:5,Qi:5,fp:2,textAlign:0,jk:0,lang:"zh-CN"}),this.X=[b],a=g.V("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.ma||(c=new g.QH(g.Goa()),g.M(this,c),this.ma=
c.element),c=b.end-b.start,(d=g.mI(this.o))&&this.X.push(new v4(b.start,c,0,b.id,d)),this.X.push(new v4(b.start,c,0,b.id,a[0]),new v4(b.start,c,0,b.id,this.ma,!0),new v4(b.start,c,0,b.id,a[1],!0)),g.gV(this.g,this.X),g.Zt(this.fa));if(this.N||g.uM(this.A))r5(this,"module-enabled",!0),this.D&&(this.D.g=this.o);(b=g.TU(this.g.app))&&b.C&&g.qP(b.C.o)}this.N=!1}};
g.h.AL=function(a){this.M.push(a);this.da.Vk()};
g.h.BL=function(a){g.Ta(this.M,a);var b=Lza(this.l,this.K)&&this.A.Ma;!this.A.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.iV(this.g,[a]);this.da.Vk()};
g.h.AT=function(a){if(a instanceof w4){var b=this.P[a.id];b&&b.D!=a&&(b.dispose(),delete this.P[a.id],b=null);b||(b=Pza(this,a))&&(this.P[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.KT=function(){Qza(this,this.X);this.X=null};
g.h.bE=function(){this.da.stop();g.Yb(this.Y);this.M.sort(g.rQ);var a=this.M;if(this.I){var b=(0,g.Id)(a,function(a){return-1==this.I.indexOf(a)},this);
b.length&&(a=b)}(0,g.B)(a,this.AT,this);g.Jb(this.P,function(a,b){this.Y[b]?(a.element.parentNode||g.lV(this.g,a.element,4),a.Mi(this.Y[b])):(a.dispose(),delete this.P[b])},this)};
g.h.RC=function(){m5(this,{},!0)};
g.h.kr=function(){var a=q5.ib;a={background:a.background,backgroundOpacity:a.Ze,charEdgeStyle:a.Vh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.mj,textOpacity:a.Eh,windowColor:q5.windowColor,windowOpacity:q5.vk};var b=n5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Uu=function(a,b){var c={};g.Ga(c,n5(this,"display-settings"));g.Ga(c,a);m5(this,c,b);this.g.R("captionssettingschanged")};
g.h.Ru=function(){!this.F&&this.loaded&&(g.Jb(this.P,function(a,b){a.dispose();delete this.P[b]},this),this.bE())};
g.h.Us=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.$c(b,-2,4);this.Uu({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&p5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.A.xb&&r5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Ca(b))break;if(g.Xb(b)){p5(this,null,!0);break}for(var d=$4(this.B.l,!0),e=0;e<d.length;e++){var f=d[e];f.l!=b.languageCode||c&&f.C!=b.languageName||(c=b.translationLanguage?Yya(f,
b.translationLanguage):f)}!c||c==this.o&&this.loaded||p5(this,c,!0)}else return this.loaded&&this.o&&this.o!=(this.D&&this.D.Mk)?s4(this.o):{};return"";case "tracklist":return this.B?(0,g.I)($4(this.B.l,!(!b||!b.includeAsr)),function(a){return s4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":c=this.kr();if(g.uM(this.A)&&b&&g.Ca(b))if(b.reset)this.RC();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Sza(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Tza(b[d],c[d]);break;case "charEdgeStyle":f[d]=Vza(b[d],c[d]);break;case "fontSizeIncrement":f[d]=Yza(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=Xza(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Uu(f,!0);c=this.kr()}c.fontFamilyOption=Wza[c.fontFamily];c.charEdgeStyle=Uza[c.charEdgeStyle];return c;case "sampleSubtitles":this.F||void 0==b||Rza(this,!!b);break;case "xmlTrack":b&&this.A.xb&&(this.F||p5(this,new g.lI({languageName:b.name}),!1,b.xml))}};
g.h.yL=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.xb&&a.push("stickyLoading","xmlTrack");return a};
g.h.zL=function(){var a=this.o;return a?{cc:a.D}:{}};
g.h.LD=function(){this.loaded&&this.o?(r5(this,"module-enabled",!1),this.unload()):p5(this,this.o||Nza(this,!0),!0)};
g.h.aP=function(){this.l.captionTracks.length&&(this.loaded&&this.unload(),this.Yz()&&this.load())};g.dY.captions=o5;})(_yt_player);
